/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-18 05:32:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addfamally_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1696897873775L));
    _jspx_dependants.put("jar:file:/C:/khs/NearByDocProj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/NearByProj/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>NearByDocHeader</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#container {\r\n");
      out.write("	background-color: #CFE8F7;\r\n");
      out.write("	margin: 10px auto;\r\n");
      out.write("	width: 430px;\r\n");
      out.write("	height: 800px;\r\n");
      out.write("	padding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#famallymanage>span {\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#famallymanage p {\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	margin-left: 65px;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	margin: 10px 20px;\r\n");
      out.write("	border: 1px solid #16151562;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("	/* Noto Sans 폰트 설정 */\r\n");
      out.write("	font-size: 12pt;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	text-decoration: inherit;\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-indent: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	margin: 10 auto;\r\n");
      out.write("	width: 57;\r\n");
      out.write("	height: 36;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".idbtn {\r\n");
      out.write("	margin-left:180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".idbtn>input {\r\n");
      out.write("	width: 57px;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	color: #2188C4;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancel {\r\n");
      out.write("	background: #DAD9D9;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	width: 57px;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	margin-left: -8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#famlist {\r\n");
      out.write("	background: white;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	overflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#famlist>input {\r\n");
      out.write("	color: #2188C4;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin-left: 300px;\r\n");
      out.write("	width: 57px;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reg {\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	background: white;\r\n");
      out.write("	color: #2188C4;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#detailfam {\r\n");
      out.write("	width: 320px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	margin: 10 auto;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#detailfam>span {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".material-symbols-outlined {\r\n");
      out.write("	font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	width: 360px;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table>td{\r\n");
      out.write("	font-size: 1px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr td:nth-child(1) {\r\n");
      out.write("	background-color: #CFE8F7;\r\n");
      out.write("	width: 90px;\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr td:nth-child(2) {\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("margin-left : 70px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	$(\".reg\").click(function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"addfamally\",\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			data:{\"fname\" : $(\"#pname\").val()\r\n");
      out.write("	      		, \"ftel\" : $(\"#tel\").val()\r\n");
      out.write("	      		, \"faddress\" : $(\"#address\").val()\r\n");
      out.write("	      		, \"fidnum\" : $(\"#idnum\").val()},\r\n");
      out.write("	      		success:function(res){\r\n");
      out.write("			    	console.log(res);\r\n");
      out.write("			    	if(res==\"can\"){\r\n");
      out.write("			    		alert(\"등록 성공\");\r\n");
      out.write("			    		location.href=\"addfamally\"\r\n");
      out.write("			    	} else {\r\n");
      out.write("			    		alert(\"등록한 사람과 주민번호가 같을 수 없습니다.\")\r\n");
      out.write("			    	}\r\n");
      out.write("			    }\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 헤더 -->\r\n");
      out.write("	");

	pageContext.include("thinheader.jsp");
	
      out.write("\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<div id=\"famallymanage\">\r\n");
      out.write("			<span style=\"text-align: left; margin: 10px 0 10px 10px\">가족관리</span>\r\n");
      out.write("			<span class=\"material-symbols-outlined\" onClick=\"history.go(-1)\"\r\n");
      out.write("				style=\"margin-left: 280px;\"> arrow_back </span> <br> <br>\r\n");
      out.write("			<!-- <form action=\"addfamally\" method=\"post\"> -->\r\n");
      out.write("				<p>이름</p>\r\n");
      out.write("				<input type=\"text\" id=\"pname\" name=\"fname\" placeholder=\"\" required=\"\">\r\n");
      out.write("				<p>전화번호</p>\r\n");
      out.write("				<input type=\"text\" id=\"tel\" name=\"ftel\" placeholder=\"-없이 숫자만 입력\" required=\"\">\r\n");
      out.write("				<p>주소</p>\r\n");
      out.write("				<input type=\"text\" id=\"address\" name=\"faddress\" placeholder=\"\" required=\"\">\r\n");
      out.write("				<p>주민등록번호</p>\r\n");
      out.write("				<input type=\"text\" id=\"idnum\" name=\"fidnum\" placeholder=\"-없이 숫자만 입력\" required=\"\">\r\n");
      out.write("				<br>\r\n");
      out.write("				<div class=\"idbtn\">\r\n");
      out.write("					<input class=\"reg\" type=button value=\"등록\"\r\n");
      out.write("						style=\"text-align: left;\">\r\n");
      out.write("				</div>\r\n");
      out.write("			<!-- </form> -->\r\n");
      out.write("			<input class=\"cancel\" type=\"button\" value=\"취소\" onclick=\"cancel\">\r\n");
      out.write("			<!-- <button class=\"cancel\" onclick=\"cancel\"><h4>취소</h4></button> -->\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"famlist\">\r\n");
      out.write("			<br>\r\n");
      out.write("			");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			<input type=\"button\" value=\"수정\" onClick=\"location.href='modifamally'\">\r\n");
      out.write("			<!-- <button><h4><a href=\"modifamally.html\">수정</a></h4></button> -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /addfamally.jsp(211,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/addfamally.jsp(211,3) '${familys}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${familys}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /addfamally.jsp(211,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("family");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			<div id=\"detailfam\">\r\n");
            out.write("				<table border=\"1\">\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td>이름</td>\r\n");
            out.write("						<td size=\"30px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${family.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td>전화번호</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${family.tel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td>주소</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${family.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("				</table>\r\n");
            out.write("			</div>\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
