/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-16 01:36:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hfooter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html >\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("  <title>Simple Footer Template with auto current Year</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Fontawesome for icons -->\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("\r\n");
      out.write("  padding: 0;\r\n");
      out.write("\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    background: #05053f;\r\n");
      out.write("    height: 120px;\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-content {\r\n");
      out.write("  display: flex;\r\n");
      out.write("\r\n");
      out.write("  align-items: center;\r\n");
      out.write("\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  \r\n");
      out.write("  margin-top:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-content h3 {\r\n");
      out.write("  font-size: 2.1rem;\r\n");
      out.write("\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("\r\n");
      out.write("  text-transform: capitalize;\r\n");
      out.write("\r\n");
      out.write("  line-height: 3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-content p {\r\n");
      out.write("  max-width: 500px;\r\n");
      out.write("\r\n");
      out.write("  margin: 10px auto;\r\n");
      out.write("\r\n");
      out.write("  line-height: 28px;\r\n");
      out.write("\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("\r\n");
      out.write("  color: #cacdd2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".socials {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("\r\n");
      out.write("  display: flex;\r\n");
      out.write("\r\n");
      out.write("  align-items: center;\r\n");
      out.write("\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("\r\n");
      out.write("  margin: 1rem 0 3rem 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".socials li {\r\n");
      out.write("  margin: 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".socials a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("  color: #fff;\r\n");
      out.write("\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".socials a i {\r\n");
      out.write("  font-size: 1.1rem;\r\n");
      out.write("\r\n");
      out.write("  width: 20px;\r\n");
      out.write("\r\n");
      out.write("  transition: color 0.4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".socials a:hover i {\r\n");
      out.write("  color: aqua;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom {\r\n");
      out.write("  background: #000;\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom p {\r\n");
      out.write("  float: left;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    word-spacing: 4px;\r\n");
      out.write("    margin-top: -57px;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom p a {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom span {\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-menu {\r\n");
      out.write(" 	float: right;\r\n");
      out.write("    margin-right: 70px;\r\n");
      out.write("    margin-top: -61px;}\r\n");
      out.write("\r\n");
      out.write(".footer-menu ul {\r\n");
      out.write("  display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-menu ul li {\r\n");
      out.write("  padding-right: 10px;\r\n");
      out.write("\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-menu ul li a {\r\n");
      out.write("  color: #cfd2d6;\r\n");
      out.write("\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-menu ul li a:hover {\r\n");
      out.write("  color: #27bcda;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 500px) {\r\n");
      out.write("  .footer-bottom p {\r\n");
      out.write("    float: none;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .footer-menu ul {\r\n");
      out.write("    display: flex;\r\n");
      out.write("\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("const year = document.getElementById(\"year\");\r\n");
      out.write("\r\n");
      out.write("year.textContent = new Date().getFullYear();\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-content\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("      <ul class=\"socials\">\r\n");
      out.write("\r\n");
      out.write("        <li><a href=\"https://www.facebook.com\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("        <li><a href=\"https://www.twitter.com\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("        <li><a href=\"https://www.google.com\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("        <li><a href=\"https://www.youtube.com\"><i class=\"fa fa-youtube\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-bottom\">\r\n");
      out.write("\r\n");
      out.write("      <p>Copyright &copy <span id=\"year\"></span> <a href=\"login\">@nearbydoc</a> </p>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"footer-menu\">\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"f-menu\">\r\n");
      out.write("\r\n");
      out.write("          <li><a href=\"\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("          <li><a href=\"\">About</a></li>\r\n");
      out.write("\r\n");
      out.write("          <li><a href=\"\">Contact</a></li>\r\n");
      out.write("\r\n");
      out.write("          <li><a href=\"\">Blog</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
