/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-17 03:15:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modiprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1696897873775L));
    _jspx_dependants.put("jar:file:/C:/khs/NearByDocProj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/NearByProj/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<title>NearByDocHeader</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#sub{\r\n");
      out.write("  width:430px;\r\n");
      out.write("  margin: 10px auto;\r\n");
      out.write("  font-size: 30px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modibtn{\r\n");
      out.write("  width: 57px;\r\n");
      out.write("  height: 36px;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  color:#2188C4;\r\n");
      out.write("  margin-left: 303px;\r\n");
      out.write("  margin-bottom: 2px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  border: 1px solid #16151562;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".canbtn{\r\n");
      out.write("  width: 57px;\r\n");
      out.write("  height: 36px;\r\n");
      out.write("  border: solid 1px;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background-color: #78818C;\r\n");
      out.write("  /* margin-left: 2px; */\r\n");
      out.write("  margin-bottom: 2px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#container {\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  margin: 10px  auto;\r\n");
      out.write("  width:430px;\r\n");
      out.write("  height:600;\r\n");
      out.write("  padding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container p input{\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    margin: 10px 20px;\r\n");
      out.write("    margin-left:60px;\r\n");
      out.write("    border: 1px solid #16151562;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    background: #ffffff;\r\n");
      out.write("    /* padding-left: 5px; */\r\n");
      out.write("    /* Noto Sans 폰트 설정 */\r\n");
      out.write("    font-size: 12pt;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    text-decoration: inherit;\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-indent: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col{\r\n");
      out.write("margin-left :60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- 헤더 -->\r\n");
      out.write("   ");
 pageContext.include("thinheader.jsp");
      out.write("\r\n");
      out.write("   <div id=\"sub\">\r\n");
      out.write("   <!--  <div >\r\n");
      out.write("      <span>\r\n");
      out.write("        <input class=\"modibtn\" type=\"button\" value=\"수정\" onclick=\"modi()\">\r\n");
      out.write("        <input class=\"canbtn\" type=\"button\" onclick=\"history.go(-1)\" value=\"취소\">\r\n");
      out.write("      </span>\r\n");
      out.write("      <br>  \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    <hr> -->\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div id=\"container\">\r\n");
      out.write("    <div>\r\n");
      out.write("    <form id=\"updateProfile\" action=\"modiprofile\" method=\"post\"> \r\n");
      out.write("	    <p class=\"col\">이름</p>\r\n");
      out.write("	    <p><input type=\"text\" id=\"name\" name=\"pname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myinfo.pname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></p>\r\n");
      out.write("	    <p class=\"col\">전화번호</p>\r\n");
      out.write("	    <p><input type=\"text\" id=\"tel\" name=\"ptel\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myinfo.ptel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \"></p>\r\n");
      out.write("	    <p class=\"col\">이메일</p>\r\n");
      out.write("	    <p><input type=\"text\" id=\"email\" name=\"pemail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myinfo.pemail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></p>\r\n");
      out.write("	    <p class=\"col\">주소</p>\r\n");
      out.write("	    <p><input type=\"text\" id=\"address\" name=\"proadaddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myinfo.proadaddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></p>\r\n");
      out.write("	    <span>\r\n");
      out.write("        <input class=\"modibtn\" type=\"submit\" value=\"수정\" onclick=\"modi()\">\r\n");
      out.write("        <input class=\"canbtn\" type=\"button\" onclick=\"history.go(-1)\" value=\"취소\">\r\n");
      out.write("      </span>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
