/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-18 11:09:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchBox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1696897873775L));
    _jspx_dependants.put("jar:file:/C:/khs/NearByDocProj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/NearByProj/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>NearByDoc</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	function toggleOtherDeptInput() {\r\n");
      out.write("		var otherDeptCheckbox = document.getElementById(\"otherDeptCheckbox\");\r\n");
      out.write("		var otherDeptInput = document.getElementById(\"otherDeptInput\");\r\n");
      out.write("\r\n");
      out.write("		if (otherDeptCheckbox.checked) {\r\n");
      out.write("			otherDeptInput.removeAttribute(\"disabled\");\r\n");
      out.write("		} else {\r\n");
      out.write("			otherDeptInput.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#selectDeptBtn\").click(function() {\r\n");
      out.write("			var selectedDept = $(\"input[name='dept']:checked\").val();\r\n");
      out.write("			if (selectedDept === '기타') {\r\n");
      out.write("				selectedDept = $(\"#otherDeptInput\").val();\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#department-input\").val(selectedDept);\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function openLocationSelectionPage() {\r\n");
      out.write("\r\n");
      out.write("		document.getElementById(\"latitude\").value = '';\r\n");
      out.write("		document.getElementById(\"longitude\").value = '';\r\n");
      out.write("		// 주소 설정 페이지 열기\r\n");
      out.write("		var locationSelectionPage = window.open(\"location.jsp\",\r\n");
      out.write("				\"LocationSelection\", \"width=500,height=600\");\r\n");
      out.write("\r\n");
      out.write("		window.addEventListener(\"message\", function(event) {\r\n");
      out.write("			// event.data에 보내진 데이터가 포함\r\n");
      out.write("			var address = event.data;\r\n");
      out.write("			var addressArr = address.split(\",\"); //주소와 위경도 분리\r\n");
      out.write("\r\n");
      out.write("			var addressInput = document.getElementById(\"address-input\");\r\n");
      out.write("			addressInput.value = addressArr[0];\r\n");
      out.write("			console.log(addressArr);\r\n");
      out.write("			console.log(addressArr[1]);\r\n");
      out.write("			if (addressArr.length == 2) {\r\n");
      out.write("				var latilong = addressArr[1].split(\":\"); //위도와 경도 분리\r\n");
      out.write("				var latitude = document.getElementById(\"latitude\");\r\n");
      out.write("				var longitude = document.getElementById(\"longitude\");\r\n");
      out.write("				latitude.value = latilong[0];\r\n");
      out.write("				longitude.value = latilong[1];\r\n");
      out.write("			}\r\n");
      out.write("			console.log(addressInput.value);\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	max-width: 425px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin: 20px auto 20px auto;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border: 2px solid #16151562;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".department-input, .address-input {\r\n");
      out.write("	padding: 13px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	font-family: 'Noto Sans', sans-serif;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	margin-bottom: 0px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	width: 97%;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-2 .icon, .container-3 .icon {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 30px;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-button {\r\n");
      out.write("	padding: 20px 20px;\r\n");
      out.write("	background-color: #cfe8f7;\r\n");
      out.write("	color: #333333;\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.3s ease;\r\n");
      out.write("	font-family: 'Noto Sans', sans-serif;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-button:hover {\r\n");
      out.write("	background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hospital {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	max-width: 395px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin: 75px auto;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	height: 65px;\r\n");
      out.write("	background-color: #dad9d9;\r\n");
      out.write("	font-family: 'Noto Sans', sans-serif;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	padding-left: 30px;\r\n");
      out.write("	color: #333333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*서치박스 안에 있는거? */\r\n");
      out.write(".material-icons {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	opacity: 0.75;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".material-icons:hover {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-2, .container-3 {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".type, .address {\r\n");
      out.write("	border-bottom: 2px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"searchhospital\" method=\"post\" id=\"searchhospital\">\r\n");
      out.write("		<input type=\"hidden\" name=\"latitude\" id=\"latitude\" /> <input\r\n");
      out.write("			type=\"hidden\" name=\"longitude\" id=\"longitude\" />\r\n");
      out.write("			\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"searchbox\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<div class=\"container-2\">\r\n");
      out.write("						<div class=\"type\">\r\n");
      out.write("							<span class=\"icon\"><i class=\"material-icons\">search</i></span>\r\n");
      out.write("							&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"text\" placeholder=\"진료과\"\r\n");
      out.write("								class=\"department-input\" name=\"department-input\" required\r\n");
      out.write("								id=\"department-input\" data-bs-toggle=\"modal\"\r\n");
      out.write("								data-bs-target=\"#myModal\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"container-3\">\r\n");
      out.write("						<div class=\"address\">\r\n");
      out.write("							<span class=\"icon\"><i class=\"material-icons\">location_on</i></span>\r\n");
      out.write("							&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"text\" placeholder=\"주소설정\"\r\n");
      out.write("								class=\"address-input\" id=\"address-input\" name=\"address-input\"\r\n");
      out.write("								onclick=\"openLocationSelectionPage()\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- <div class=\"button\"> -->\r\n");
      out.write("					<button class=\"search-button\" type=\"submit\">병원 찾기</button>\r\n");
      out.write("					<!-- </div> -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("	<!-- The Modal -->\r\n");
      out.write("	<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal Header -->\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h4 class=\"modal-title\">진료과목을 선택해주세요</h4>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal body -->\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"내과\"> 내과</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"정형외과\">\r\n");
      out.write("							정형외과</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"외과\"> 외과</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"피부과\"> 피부과\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"산부인과\">\r\n");
      out.write("							산부인과</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"정신건강의학과\">\r\n");
      out.write("							정신건강의학과</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"이비인후과\">\r\n");
      out.write("							이비인후과</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" value=\"소아과\"> 소아과\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><input type=\"radio\" name=\"dept\" id=\"otherDeptCheckbox\"\r\n");
      out.write("							value=\"기타\" onchange=\"toggleOtherDeptInput()\"> 기타 <input\r\n");
      out.write("							type=\"text\" name=\"otherDept\" id=\"otherDeptInput\"\r\n");
      out.write("							placeholder=\"기타 진료과목 입력\" disabled></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal footer -->\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("						data-bs-dismiss=\"modal\" id=\"selectDeptBtn\">선택 완료</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
